<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<META NAME="description" content="North Star River Expeditions runs 3 to 6 day commercially outfitted whitewater rafting trips on the Snake River in Hells Canyon and the Lower Main Salmon River. Our trips are first class, providing all equipment needed for the trip, gourmet Dutch oven cooking, and a staff of experienced, friendly professional guides.>
<META name="keywords" content="whitewater river expeditions, whitewater rafting in the Snake River, Snake River whitewater rafting, Salmon River whitewater rafting, whitewater rafting in the Salmon River, Idaho whitewater rafting, whitewater rafting in Idaho, river expeditions, wildlife, boating, snake, salmon, petroglyphs, Idaho, outdoors, hiking, elk, sheep, white water, rapids, kayak, pontoon, rafts">

<title>North Star River Expeditions</title>

<style type='text/css'>
	A:hover { color:#0044bb; }
	A:link { text-decoration: none; }
	A:active { text-decoration: none; }
	A:visited { text-decoration: none; }
</style>

<script language="javascript"><!--

if (document.images) {
	var iconTop = new Image();
	iconTop.src = "top1.gif";
	var iconTopOn = new Image();
	iconTopOn.src = "top2.gif"
	statusTop = "Return to top of page";
	
	var iconLogo = new Image();
	iconLogo.src = "logo_white.gif";
	var iconLogoOn = new Image();
	iconLogoOn.src = "logo_white2.gif"
	statusLogo = "Return to home page";
}

function iconOver(name){
	if (document.images) {
  		document.images[name].src=eval("icon"+name+"On.src");
		status=eval("status"+name);
	}
}

function iconOut(name){
	if (document.images) {
  		document.images[name].src=eval("icon"+name+".src");
		status="";
	}
}

//-->
</script>

</head>
<body background="mapback.jpg" link="#946330" vlink="#946330" alink="#946330">
<a name="top"></a>

<table width="100%" cellspacing=0 border=0 cellpadding=2 border=0>
<tr>
	<td valign="top" rowspan=2>
<font face="Tahoma, Arial, Helvetica" size=2>