<tr>
	<td rowspan=6>&nbsp;</font></td>
	<td><font face="Arial, Helvetica" size=2>Breakfast</font></td>
	<td><font face="Arial, Helvetica" size=2><b>8:00 am</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>On the River</font></td>
	<td><font face="Arial, Helvetica" size=2><b>10:00 to 10:30 am</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Lunch</font></td>
	<td><font face="Arial, Helvetica" size=2><b>12:00 pm</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Arrive in Camp for Evening</font></td>
	<td><font face="Arial, Helvetica" size=2><b>4:00 to 5:00 pm</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Hour'd eourves and Cocktails</font></td>
	<td><font face="Arial, Helvetica" size=2><b>6:00 pm</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Dinner</font></td>
	<td><font face="Arial, Helvetica" size=2><b>8:00 pm</b></font></td>