<font size=3>Mountain Time Zone</font>
</center>
<p>
<table border=0 cellspacing=1 cellpadding=1>
<tr>
	<td colspan=3 bgcolor="#000000">
	<font face="Arial, Helvetica" size=3 color="#ffffff">&nbsp;<b>Day Before The Launch Date</b></font></td>
<tr>
	<td rowspan=2 width="5%">&nbsp;</font></td>
	<td><font face="Arial, Helvetica" size=2>Pre-Trip Meeting</font></td>
	<td><font face="Arial, Helvetica" size=2><b>8:00 pm</b></font></td>
<tr>
	<td colspan=2><font face="Arial, Helvetica" size=2><blockquote>
Hotel McCall, 1101 North 3rd Street, McCall, Idaho, 208-634-8105.<br>
We will make initial introductions, pass out waterproof duffel, go over the itinerary, arrange for picking up everyone the next morning, and cover any last minute questions or adjustments for the trip.
	</blockquote></font></td>

<tr>
	<td colspan=3 bgcolor="#000000">
	<font face="Arial, Helvetica" size=3 color="#ffffff">&nbsp;<b>Trip-Day 1</b></font></td>
<tr>
	<td rowspan=8 width="5%">&nbsp;</font></td>
	<td><font face="Arial, Helvetica" size=2>Departure to Hells Canyon</font></td>
	<td><font face="Arial, Helvetica" size=2><b>7:00 am</b></font></td>
<tr>
	<td colspan=2><font face="Arial, Helvetica" size=2><blockquote>
Meet the bus to load duffel and leave town We recommend you eat breakfast before we leave.  The scenic bus ride will be about 3 hours plus any restroom stops we make.
	</blockquote></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Arrive at the Snake River in Hells Canyon</font></td>
	<td><font face="Arial, Helvetica" size=2><b>10:30 am</b></font></td>
<tr>
	<td colspan=2><font face="Arial, Helvetica" size=2><blockquote>
Unload bags, see Visitor Center, and get on the river.
	</blockquote></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Lunch</font></td>
	<td><font face="Arial, Helvetica" size=2><b>1:00 pm</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Arrive in Camp for Evening</font></td>
	<td><font face="Arial, Helvetica" size=2><b>4:00 to 5:00 pm</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Hors 'd oeuvres and Cocktails</font></td>
	<td><font face="Arial, Helvetica" size=2><b>6:00 pm</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Dinner</font></td>
	<td><font face="Arial, Helvetica" size=2><b>8:00 pm</b></font></td>