<tr>
	<td rowspan=6>&nbsp;</font></td>
	<td><font face="Arial, Helvetica" size=2>Breakfast</font></td>
	<td><font face="Arial, Helvetica" size=2><b>8:00 am</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>On the River</font></td>
	<td><font face="Arial, Helvetica" size=2><b>10:00 to 10:30 am</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Lunch</font></td>
	<td><font face="Arial, Helvetica" size=2><b>1:00 pm</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Arrive at Take-out and load onto bus</font></td>
	<td><font face="Arial, Helvetica" size=2><b>2:00pm</b></font></td>
<tr>
	<td><font face="Arial, Helvetica" size=2>Arrive in McCall</font></td>
	<td><font face="Arial, Helvetica" size=2><b>4:30pm</b></font></td>
</table>
<p>

<font size=4><b>NOTE:</b></font>  ALL times quoted from the time we leave the Put-In at Pine Bar are approximate, can be very flexible, and depend upon activities we choose to do during the day, water levels and conditions, and the weather.  We have snacks and drinks available throughout the day as needed.  
<p>
Please notify us of any dietary restrictions or medical conditions that we should be made aware of, so we can meet your needs accordingly.
<p>
Following is a list of possible activities and sites to see while we are on the river.  PLEASE let us know ahead of time which activities you might be interested in, and keep us updated throughout the trip so we can best meet your expectations and ensure you will have a wonderful time!
<p>
<ul>
<li>Visit Indian pictograph and petroglyph sites, historic cabins and ranches, or Indian dwellings
<li>Side hikes up canyons, creeks, or to various view points, vistas, or ridge lines
<li>Time for swimming, naps, sunbathing, etc.
<li>Fishing
<li>Kayaking
<li>Photography stops
</ul>

</body>
</html>