<font face="Tahoma, Arial, Helvetica" size=2>
• <a href="rate-date.shtml">Rates and Dates</a><br>
• <a href="booking.shtml">Book a trip</a><br>
• <a href="snake.shtml">Snake River</a><br>
• <a href="salmon.shtml">Salmon River</a><br>
• <a href="fishing.shtml">Fishing</a><br>
• <a href="wildlife.shtml">Wildlife</a><br>
• <a href="history-hiking.shtml">History & Hiking</a><br>
• <a href="boats.shtml">Boats</a><br>
• <a href="equipment.shtml">Equipment</a><br>
• <a href="food.shtml">Food, etc.</a><br>
• <a href="map.shtml">Map</a>
	</font>
	</td>
<tr>
	<td bgcolor="#e0bf82" align="center">
	<font face="Tahoma, Arial, Helvetica" size=2>
877-610-3200<br>
<a href="mailto:vacation@northstar-rafting.com">or e-mail us</a>
</font>